services:
  express:
    build: ./backend
    env_file:
      - .env
    environment:
      DB_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      postgresDB:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "3001:3001"
    links:
      - postgresDB:postgresDB
  postgresDB:
    image: postgres
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: docker
    ports:
      - "15151:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U docker" ]
      interval: 10s
      timeout: 5s
      retries: 5
  redis:
    image: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
  test:
    build: ./backend
    env_file:
      - .env.test
    environment:
      DB_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - postgresDB
      - redis
    command: sh -c "npm install && npm test"
    volumes:
      - ./backend:/web